### ISSUE TITLE
RegEx pattern in go code doesn't match the yaml and cause differing behavior

### ISSUE THREAD

**Issue by TexanHogman** [salrashid123/envoy_control#1]
Thanks for the demo

https://github.com/salrashid123/envoy_control/blob/master/src/main.go#L278

should be changed to match 

https://github.com/salrashid123/envoy_control/blob/master/bbc.yaml#L29

As is, `curl -v  localhost:10000/robots.txt` will return a 404 with your dynamic configuration but using bbc.yaml works fine.

**Comment by salrashid123** [comment]
thanks for the report, fixed it in:
  https://github.com/salrashid123/envoy_control/commit/9279b323613ff5f233af99268cb2c3d3fe0d7471

---
also fixed an error in the cache snapshot preventing compiling.

i'll also have a todo later to make it more useful than just one 'static' snapshot (i.,e  periodically keep updating the host that is proxied every min or so; multiple snapshots, etc;  i'll add it in later but if you get to test that out, i'll gladly take a PR!)

**Comment by salrashid123** [comment]
for ref: added in the snapshot loop now:
 https://github.com/salrashid123/envoy_control#start-control-plane

the server now runs for 180s where each min it will change the target host where it gets the robots file.
